name = "dim-alert"
main = "src/index.js"
compatibility_date = "2023-10-16"
node_compat=true
usage_model = "bundled"
env = { }
[vars]
SHOPIFY_ENDPOINT = ""
NACELLE_ENDPOINT = ""
SLACK_WEBHOOK_URL = ""
SHOPIFY_ADMIN_ENDPOINT = ""
SHOPIFY_STOREFRONT_TOKEN = ""
SHOPIFY_ADMIN_TOKEN = ""
[triggers]
crons = [ "5 */1 * * *", "7 */1 * * *", "9 */1 * * *" ]
